Repository swimme/react-diary-client, pull requests merged in 2021-06, with the labels that each got.

#13 다이어리 api
  common/api/axios.ts
  common/api/endpoints.ts
  common/api/postAPI.ts
  pages/_app.tsx
  server/routes/post.ts
  server/service/postService.ts
  server/utils/decodeAccessCookie.ts
  share/constant.ts
  share/interfaces/post.ts
  views/index/index.tsx
Labels: client, server

#19 메인 페이지 레이아웃/ 페이지네이션
  package.json
  pages/_app.tsx
  share/utils/mock-data.ts
  views/index/diarybox.tsx
  views/index/index.tsx
  views/index/paging.css
  views/index/search.tsx
  views/index/styles.ts
  yarn.lock
Labels: client

#39 [css] 글로벌 레이아웃 너비 수정
  views/components/header/index.tsx
  views/components/header/styles.ts
  views/components/layout/styles.ts
  views/components/sidebar/styles.ts
  views/index/diarybox/styles.ts
  views/index/styles.ts
Labels: hotfix
